on: ["push", "pull_request"]

name: CI

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.16

    - name: Build
      run: go build -v ./...

    - name: Get cover tooling (1/2)
      run: go get golang.org/x/tools/cmd/cover

    - name: Get cover tooling (2/2)
      run: go get github.com/mattn/goveralls

    - name: Test
      run: go test -v -coverprofile=coverage.out

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        path-to-lcov: coverage.out
